version: "3.9"

services:
  postgres:
    image: postgres
    container_name: ecommerce_postgres_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nevecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - nevecommerce:/var/lib/postgres
    
  redis:
    image: redis
    container_name: ecommerce_redis_container
    ports:
      - 6379:6379
    restart: always
    environment:
      REDIS_PASS: password
      REDIS_URI: redis://default:password@redis:6379
    volumes:
      - nevecommerce:/var/lib/redis

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - ${PORT}:3001
  #   tty: true
  #   depends_on:
  #     - postgres
  #   restart: always
  #   volumes:
  #     - type: bind
  #       source: .
  #       target: /app
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}

volumes:
  nevecommerce: